# Generated by Django 4.2.30 on 2026-04-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cake_type', models.CharField(choices=[('Regular', 'Regular'), ('Special', 'Special')], max_length=20)),
                ('ingredients', models.JSONField(default=list)),
                ('emoji', models.CharField(default='🎂', max_length=10)),
                ('price_small', models.DecimalField(decimal_places=2, default=15.0, max_digits=6)),
                ('price_medium', models.DecimalField(decimal_places=2, default=25.0, max_digits=6)),
                ('price_large', models.DecimalField(decimal_places=2, default=40.0, max_digits=6)),
                ('bake_sec_small', models.IntegerField(default=30)),
                ('bake_sec_medium', models.IntegerField(default=50)),
                ('bake_sec_large', models.IntegerField(default=75)),
                ('ingredient_cost_pct', models.FloatField(default=0.3)),
                ('is_unlocked', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(unique=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('worker_salaries', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ingredient_costs', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('waste_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orders_fulfilled', models.IntegerField(default=0)),
                ('orders_expired', models.IntegerField(default=0)),
                ('cakes_baked', models.IntegerField(default=0)),
                ('cakes_wasted', models.IntegerField(default=0)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_satisfaction', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Sweet Layers', max_length=100)),
                ('day', models.IntegerField(default=1)),
                ('money', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('reputation', models.IntegerField(default=50)),
                ('is_open', models.BooleanField(default=False)),
                ('game_started', models.BooleanField(default=False)),
                ('day_started_at', models.DateTimeField(blank=True, null=True)),
                ('next_order_at', models.DateTimeField(blank=True, null=True)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fulfilled', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Game State',
            },
        ),
        migrations.CreateModel(
            name='Oven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('industrial', 'Industrial')], default='basic', max_length=20)),
                ('speed_bonus', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_on_day', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier')], max_length=20)),
                ('salary_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hired_on_day', models.IntegerField()),
                ('skill_level', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_oven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_workers', to='game.oven')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField(default=0)),
                ('pieces', models.IntegerField(default=0)),
                ('want_fresh', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('day_placed', models.IntegerField()),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.cakerecipe')),
            ],
        ),
        migrations.CreateModel(
            name='BakedCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('is_baking', models.BooleanField(default=True)),
                ('baked_time', models.DateTimeField(blank=True, null=True)),
                ('bake_finish_at', models.DateTimeField(blank=True, null=True)),
                ('bake_duration_sec', models.IntegerField(default=30)),
                ('remaining_slices', models.IntegerField(default=4)),
                ('day_baked', models.IntegerField(default=1)),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('oven', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cakes', to='game.oven')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baked_instances', to='game.cakerecipe')),
            ],
        ),
    ]
