# Generated by Django 4.2.30 on 2026-04-30 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='bake_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='service_speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='special_skill',
            field=models.CharField(choices=[('none', 'None'), ('fresh_expert', 'Fresh Expert'), ('multitasker', 'Multi-tasker'), ('speed_demon', 'Speed Demon')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='worker',
            name='target_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dedicated_workers', to='game.cakerecipe'),
        ),
        migrations.AddField(
            model_name='worker',
            name='work_mode',
            field=models.CharField(choices=[('orders_only', 'Orders Only'), ('casual', 'Casual'), ('cake_only', 'Cake Only')], default='orders_only', max_length=20),
        ),
    ]
