# Generated by Codex on 2026-05-14

from django.db import migrations, models


def seed_player_unlocked_recipes(apps, schema_editor):
    GameState = apps.get_model("game", "GameState")
    CakeRecipe = apps.get_model("game", "CakeRecipe")

    starter_ids = set(CakeRecipe.objects.filter(is_starter=True).values_list("id", flat=True))
    legacy_unlocked_ids = set(CakeRecipe.objects.filter(is_unlocked=True).values_list("id", flat=True))
    unlocked_ids = list(starter_ids | legacy_unlocked_ids)

    if not unlocked_ids:
        return

    for state in GameState.objects.all():
        state.unlocked_recipes.add(*unlocked_ids)


def clear_player_unlocked_recipes(apps, schema_editor):
    GameState = apps.get_model("game", "GameState")
    for state in GameState.objects.all():
        state.unlocked_recipes.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_bakedcake_manual_result_mult"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamestate",
            name="unlocked_recipes",
            field=models.ManyToManyField(
                blank=True,
                related_name="unlocked_by_states",
                to="game.cakerecipe",
            ),
        ),
        migrations.RunPython(seed_player_unlocked_recipes, clear_player_unlocked_recipes),
    ]
