# Generated by Django 4.2.30 on 2026-05-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_worker_bake_speed_worker_service_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HireableWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier')], max_length=20)),
                ('skill_level', models.IntegerField(default=1)),
                ('bake_speed', models.IntegerField(default=1)),
                ('service_speed', models.IntegerField(default=1)),
                ('special_skill', models.CharField(default='none', max_length=30)),
                ('salary_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('hire_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available_from_day', models.IntegerField(default=1)),
                ('expires_on_day', models.IntegerField(default=4)),
                ('is_hired', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='customerorder',
            name='order_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent'), ('bulk', 'Bulk')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='pool_refreshed_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='worker',
            name='special_skill',
            field=models.CharField(choices=[('none', 'None'), ('fresh_expert', 'Fresh Expert'), ('multitasker', 'Multi-tasker'), ('speed_demon', 'Speed Demon'), ('sweet_tooth', 'Sweet Tooth'), ('economist', 'Economist')], default='none', max_length=30),
        ),
    ]
