# Generated by Django 4.2.30 on 2026-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_hireableworker_customerorder_order_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(default='ℹ️', max_length=10)),
                ('message', models.CharField(max_length=300)),
                ('log_type', models.CharField(default='info', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='unlock_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='unlock_message',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='unlock_rep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='customer_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('patient', 'Patient'), ('impatient', 'Impatient'), ('picky', 'Picky'), ('bulk_buyer', 'Bulk Buyer'), ('vip', 'VIP'), ('regular', 'Regular'), ('inspector', 'Inspector')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='best_seller',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dayreport',
            name='best_seller_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='active_event',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='briefing_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='critic_fresh_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='event_counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='owned_upgrades',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='rush_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oven',
            name='bakes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worker',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='worker',
            name='raise_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='raise_requested_day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
