# Generated by Codex on 2026-05-14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_admin_configs(apps, schema_editor):
    from game import game_engine
    from game import models as game_models

    OvenTypeConfig = apps.get_model('game', 'OvenTypeConfig')
    KitchenUpgradeConfig = apps.get_model('game', 'KitchenUpgradeConfig')
    DailyEventConfig = apps.get_model('game', 'DailyEventConfig')
    WorkerSkillConfig = apps.get_model('game', 'WorkerSkillConfig')
    WorkerTraitConfig = apps.get_model('game', 'WorkerTraitConfig')
    CustomerTypeConfig = apps.get_model('game', 'CustomerTypeConfig')
    CourseConfig = apps.get_model('game', 'CourseConfig')
    SalaryRangeConfig = apps.get_model('game', 'SalaryRangeConfig')
    GameBalanceConfig = apps.get_model('game', 'GameBalanceConfig')

    for sort_order, (tier, cfg) in enumerate(game_engine.OVEN_CATALOG.items(), 1):
        OvenTypeConfig.objects.update_or_create(
            code=tier,
            defaults={
                'name': cfg['name'],
                'tier': cfg['tier'],
                'cost': cfg['cost'],
                'speed_bonus': cfg['speed_bonus'],
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    for sort_order, (code, cfg) in enumerate(game_models.KITCHEN_UPGRADES.items(), 1):
        KitchenUpgradeConfig.objects.update_or_create(
            code=code,
            defaults={
                'name': cfg['name'],
                'emoji': cfg.get('emoji', ''),
                'cost': cfg['cost'],
                'description': cfg.get('desc', ''),
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    for sort_order, cfg in enumerate(game_models.DAILY_EVENTS, 1):
        DailyEventConfig.objects.update_or_create(
            code=cfg['id'],
            defaults={
                'name': cfg['title'],
                'title': cfg['title'],
                'icon': cfg.get('icon', ''),
                'message': cfg.get('msg', ''),
                'event_type': cfg.get('type', 'info'),
                'weight': cfg.get('weight', 1),
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    for sort_order, (code, cfg) in enumerate(game_models.SKILL_CATALOGUE.items(), 1):
        WorkerSkillConfig.objects.update_or_create(
            code=code,
            defaults={
                'name': cfg['name'],
                'role': cfg.get('role', ''),
                'rarity': cfg.get('rarity', 'standard'),
                'description': cfg.get('desc', ''),
                'effect': cfg.get('effect', ''),
                'value': cfg.get('value', 1.0),
                'is_negative': cfg.get('negative', False),
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    sort_order = 1
    for trait_type, traits in (('positive', game_models.POSITIVE_TRAITS), ('negative', game_models.NEGATIVE_TRAITS)):
        for code, cfg in traits.items():
            WorkerTraitConfig.objects.update_or_create(
                code=code,
                defaults={
                    'name': cfg['name'],
                    'trait_type': trait_type,
                    'icon': cfg.get('icon', ''),
                    'description': cfg.get('desc', ''),
                    'sort_order': sort_order,
                    'is_enabled': True,
                },
            )
            sort_order += 1

    for sort_order, (code, cfg) in enumerate(game_models.CUSTOMER_TYPE_META.items(), 1):
        tip_min, tip_max = cfg.get('tip_range', (0, 0))
        CustomerTypeConfig.objects.update_or_create(
            code=code,
            defaults={
                'name': code.replace('_', ' ').title(),
                'icon': cfg.get('icon', ''),
                'patience_mult': cfg.get('patience_mult', 1.0),
                'revenue_mult': cfg.get('revenue_mult', 1.0),
                'tip_min': tip_min,
                'tip_max': tip_max,
                'weight': cfg.get('weight', 1),
                'rep_on_fail': cfg.get('rep_on_fail', 0),
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    for sort_order, ((from_rarity, to_rarity), cfg) in enumerate(game_models.COURSE_CONFIG.items(), 1):
        CourseConfig.objects.update_or_create(
            from_rarity=from_rarity,
            to_rarity=to_rarity,
            defaults={
                'code': f'{from_rarity}_to_{to_rarity}',
                'name': f'{from_rarity.title()} to {to_rarity.title()}',
                'cost': cfg['cost'],
                'days': cfg['days'],
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )

    sort_order = 1
    for role, levels in game_engine.SALARY_RANGES.items():
        for skill_level, values in levels.items():
            SalaryRangeConfig.objects.update_or_create(
                role=role,
                skill_level=skill_level,
                defaults={
                    'code': f'{role}_{skill_level}',
                    'name': f'{role.title()} Level {skill_level}',
                    'salary_min': values[2],
                    'salary_max': values[3],
                    'hire_cost_min': values[0],
                    'hire_cost_max': values[1],
                    'sort_order': sort_order,
                    'is_enabled': True,
                },
            )
            sort_order += 1

    balance_rows = [
        ('starting_money', 'Starting Money', 'decimal', '500'),
        ('starting_reputation', 'Starting Reputation', 'int', '50'),
        ('default_day_duration_seconds', 'Default Day Duration Seconds', 'int', '300'),
        ('event_roll_chance', 'Daily Event Roll Chance', 'float', '0.35'),
        ('game_over_debt_limit', 'Game Over Debt Limit', 'decimal', '-50'),
    ]
    for sort_order, (code, name, value_type, value) in enumerate(balance_rows, 1):
        GameBalanceConfig.objects.update_or_create(
            code=code,
            defaults={
                'name': name,
                'value_type': value_type,
                'value': value,
                'sort_order': sort_order,
                'is_enabled': True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_gamestate_unlocked_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBalanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('decimal', 'Decimal'), ('text', 'Text'), ('json', 'JSON')], default='float', max_length=20)),
                ('value', models.CharField(blank=True, default='', max_length=200)),
                ('data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Game Balance Setting',
                'verbose_name_plural': 'Base Game Studio - Game Balance Settings',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OvenTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('tier', models.CharField(max_length=20, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('speed_bonus', models.FloatField(default=1.0)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Oven Type',
                'verbose_name_plural': 'Base Game Studio - Oven Types',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='KitchenUpgradeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('emoji', models.CharField(blank=True, default='', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Kitchen Upgrade',
                'verbose_name_plural': 'Base Game Studio - Kitchen Upgrades',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DailyEventConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=300)),
                ('event_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('challenge', 'Challenge'), ('info', 'Info')], default='info', max_length=20)),
                ('weight', models.IntegerField(default=1)),
                ('effect_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Daily Event',
                'verbose_name_plural': 'Base Game Studio - Daily Events',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkerSkillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('role', models.CharField(max_length=20)),
                ('rarity', models.CharField(default='standard', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('effect', models.CharField(blank=True, default='', max_length=60)),
                ('value', models.FloatField(default=1.0)),
                ('is_negative', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Worker Skill',
                'verbose_name_plural': 'Base Game Studio - Worker Skills',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='WorkerTraitConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('trait_type', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Worker Trait',
                'verbose_name_plural': 'Base Game Studio - Worker Traits',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('patience_mult', models.FloatField(default=1.0)),
                ('revenue_mult', models.FloatField(default=1.0)),
                ('tip_min', models.FloatField(default=0.0)),
                ('tip_max', models.FloatField(default=0.0)),
                ('weight', models.IntegerField(default=1)),
                ('rep_on_fail', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Customer Type',
                'verbose_name_plural': 'Base Game Studio - Customer Types',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('from_rarity', models.CharField(max_length=20)),
                ('to_rarity', models.CharField(max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('days', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Course Rule',
                'verbose_name_plural': 'Base Game Studio - Course Rules',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('role', models.CharField(max_length=20)),
                ('skill_level', models.IntegerField(default=1)),
                ('salary_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salary_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hire_cost_min', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hire_cost_max', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Salary Range',
                'verbose_name_plural': 'Base Game Studio - Salary Ranges',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=120)),
                ('before_summary', models.JSONField(blank=True, default=dict)),
                ('after_summary', models.JSONField(blank=True, default=dict)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to='game.gamestate')),
            ],
            options={
                'verbose_name': 'Player Control Center - Admin Action Log',
                'verbose_name_plural': 'Player Control Center - Admin Action Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_model', models.CharField(choices=[('oven_type', 'Oven Types'), ('kitchen_upgrade', 'Kitchen Upgrades'), ('daily_event', 'Daily Events'), ('worker_skill', 'Worker Skills'), ('worker_trait', 'Worker Traits'), ('customer_type', 'Customer Types'), ('course', 'Course Rules'), ('salary_range', 'Salary Ranges'), ('game_balance', 'Game Balance Settings')], max_length=40)),
                ('payload', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base Game Studio - Config Import Job',
                'verbose_name_plural': 'Base Game Studio - Config Import Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notes', to='game.gamestate')),
            ],
            options={
                'verbose_name': 'Player Control Center - Admin Note',
                'verbose_name_plural': 'Player Control Center - Admin Notes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('game_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_snapshots', to='game.gamestate')),
            ],
            options={
                'verbose_name': 'Player Control Center - Player Snapshot',
                'verbose_name_plural': 'Player Control Center - Player Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(seed_admin_configs, migrations.RunPython.noop),
    ]
