# Generated by Django 4.2.30 on 2026-05-14 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_admin_control_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('emoji', models.CharField(default='☕', max_length=10)),
                ('brew_time_sec', models.IntegerField(default=15)),
                ('price', models.DecimalField(decimal_places=2, default=5.0, max_digits=6)),
                ('ingredient_cost_pct', models.FloatField(default=0.2)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('is_starter', models.BooleanField(default=False)),
                ('unlock_day', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('manager', 'Manager'), ('barista', 'Barista')], max_length=20),
        ),
        migrations.CreateModel(
            name='BrewStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('purchased_on_day', models.IntegerField(default=1)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('brews_count', models.IntegerField(default=0)),
                ('game_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brew_stations', to='game.gamestate')),
            ],
        ),
        migrations.CreateModel(
            name='BrewingDrink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_brewing', models.BooleanField(default=True)),
                ('brew_finish_at', models.DateTimeField(blank=True, null=True)),
                ('brew_duration_sec', models.IntegerField(default=15)),
                ('day_brewed', models.IntegerField(default=1)),
                ('ingredient_cost', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('game_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brewing_drinks', to='game.gamestate')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.drinkrecipe')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.brewstation')),
            ],
        ),
    ]
