# Generated by Django 4.2.30 on 2026-05-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_eventlog_cakerecipe_unlock_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hireableworker',
            name='special_skill',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='raise_amount',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='raise_requested_day',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='special_skill',
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='is_starter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='secret_available_from_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='secret_expires_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cakerecipe',
            name='shop_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='satisfaction',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='course_discount_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='todays_guest_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hireableworker',
            name='skill_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='hireableworker',
            name='skill_rarity',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='course_finish_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='course_target_rarity',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='worker',
            name='skill_id',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='worker',
            name='skill_rarity',
            field=models.CharField(default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='bake_sec_large',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='bake_sec_medium',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='bake_sec_small',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='cake_type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Special', 'Special'), ('Secret', 'Secret')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='is_unlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='price_large',
            field=models.DecimalField(decimal_places=2, default=52.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='price_medium',
            field=models.DecimalField(decimal_places=2, default=32.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='cakerecipe',
            name='price_small',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='customerorder',
            name='customer_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('patient', 'Patient'), ('impatient', 'Impatient'), ('picky', 'Picky'), ('bulk_buyer', 'Bulk Buyer'), ('vip', 'VIP'), ('regular', 'Regular'), ('inspector', 'Inspector'), ('critic', 'Critic'), ('todays', "Today's Guest")], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='hireableworker',
            name='role',
            field=models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('manager', 'Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='role',
            field=models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('manager', 'Manager')], max_length=20),
        ),
    ]
