# Generated by Django 4.2.30 on 2026-05-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_drinkrecipe_alter_worker_role_brewstation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
