# Generated by Django 4.2.30 on 2026-05-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_eventlog_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hireableworker',
            name='role',
            field=models.CharField(choices=[('baker', 'Baker'), ('cashier', 'Cashier'), ('waiter', 'Waiter'), ('manager', 'Manager'), ('barista', 'Barista')], max_length=20),
        ),
    ]
