# Generated by Django 4.2.30 on 2026-05-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_hireableworker_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='lifecycle_state',
            field=models.CharField(choices=[('entering', 'Entering'), ('queued', 'Queued'), ('ordering', 'Ordering'), ('waiting_for_food', 'Waiting for Food'), ('seated', 'Seated'), ('paying', 'Paying'), ('fulfilled', 'Fulfilled'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='queue_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='table_slot',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='tables_count',
            field=models.IntegerField(default=2),
        ),
    ]
