# Generated by Django 4.2.30 on 2026-05-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_customerorder_lifecycle_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestate',
            name='cashier_stands',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='gamestate',
            name='max_queue_size',
            field=models.IntegerField(default=3),
        ),
    ]
